#!/usr/bin/env bash
# This script use scp to transfer a file locally to a remote server
if [ "$#" -ne 3 ]
then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp "$3"@"$2":"$1" ~/ -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null -i "$4"
fi
