#!/usr/bin/env bash
# This script use scp to transfer a file locally to a remote server
if [ "$#" -ne 3 ]
then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i "$4" -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null "$1" "$3"@"$2":~/
fi
