#!/usr/bin/env bash
# This script install nginx on a server and configure the home page
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
# sudo service nginx start
# echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# sudo cp index.nginx-debian.html /var/www/html
sudo service nginx restart
