#!/usr/bin/env bash
# This script install nginx on a server and configure the home page
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > index.nginx-debian.html
cp index.nginx-debian.html /var/www/html
sudo service nginx restart
