#!/usr/bin/env bash
# This script configure a new ubuntu server and redirect a page
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '51i\\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo sed -i '52i\\tlocation = /error_404.html {\n\t\troot /var/www/html;\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx reload
