#!/usr/bin/env bash
# This script configure my 2 server to add custom header for load balancing
# server_id=$(cat /etc/hosts | grep "web" | cut -d " " -f3)
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "52i\\\t\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sudo service nginx reload
