#!/usr/bin/env bash
# Changing nginx port
apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo echo "1" /proc/sys/net/ipv6/conf/all/disable_ipv6
service nginx start
