#!/usr/bin/env bash
# A script printing info on /etc/passwd with filters
file="/etc/passwd"
while read -r line; do
	guid=$(echo "$line" | cut -d: -f4)
	hd=$(echo "$line" | cut -d: -f6)
	d=$(echo "$line" | cut -d: -f7)
	ps=$(echo "$line" | cut -d: -f2)
	usr=$(echo "$line" | cut -d: -f1)
	uid=$(echo "$line" | cut -d: -f3)
	uid_info=$(echo "$line" | cut -d: -f5)
	echo "The user $usr is part of the $guid gang, lives in $hd and rides $d. $uid's place is protected by the passcode $ps, more info about the user here: $uid_info"
done < $file
