#!/usr/bin/env bash
#Part 2 of networking basics
tmp_file=host
cp /etc/hosts $tmp_file

sudo sed -i 's/127.0.0.1/127.0.0.2/g' $tmp_file
sudo sed -i 's/157.240.11.35/8.8.8.8/g' $tmp_file

cp -f $tmp_file /etc/hosts
