#!/usr/bin/env bash
# This file start apache and provides a page
sudo apt update 
sudo apt install apache2
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf
sudo service apache2 start
