#!/usr/bin/env bash
# This script defines nginx user limitations
# sudo -u nginx start nginx.service
pkill apache2
# chown nginx:nginx /etc/nginx/nginx.conf
# chmod u+r+w+x /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx-sites-available/default
sudo -u nginx service nginx start
